<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN9twpc6\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN9twpc6/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerN9twpc6.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerN9twpc6\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerN9twpc6\appDevDebugProjectContainer([
    'container.build_hash' => 'N9twpc6',
    'container.build_id' => '3d67cc8b',
    'container.build_time' => 1597993811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN9twpc6');
